name: Build and Release the REG

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - release

jobs:
  BuildandRelease:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Setup branch name
      run: |
          # Strip git ref prefix from version
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV

    - name: Package application
      run: make global_build

    - name: CREATE REG DIR
      run: make make_output_dir

    - name: COPY NECESSARY LOGS
      run: make copy_necessary_files

    - name:  Unzip Application
      run: make unzip_app

    - name:  Copy libraries
      run: make copy_libs

    - name:  Zip the final directory
      run: make zip_the_final_directory


